plugins { id 'com.android.application' }

android {
    namespace 'com.snowworks.ariana'
    compileSdk 35

    defaultConfig {
        applicationId 'com.snowworks.ariana'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '0.1.0'
    }

    buildTypes {
        debug { minifyEnabled false }
        release { minifyEnabled false }
    }
}
